# Generated by Django 4.2.20 on 2025-04-16 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_ledger', '0012_optional_deposit_sales_contract_reference'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicaladjustment',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical adjustment', 'verbose_name_plural': 'historical adjustments'},
        ),
        migrations.AlterModelOptions(
            name='historicaldeposit',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical deposit', 'verbose_name_plural': 'historical deposits'},
        ),
        migrations.AlterModelOptions(
            name='historicalledger',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical ledger', 'verbose_name_plural': 'historical ledgers'},
        ),
        migrations.AlterModelOptions(
            name='historicalreversal',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical reversal', 'verbose_name_plural': 'historical reversals'},
        ),
        migrations.AlterModelOptions(
            name='historicaltransaction',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical transaction', 'verbose_name_plural': 'historical transactions'},
        ),
    ]
