# Generated by Django 5.2 on 2025-04-16 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openedx_ledger', '0013_alter_historicaladjustment_options_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='transaction',
            new_name='idx_ledger_content_exc',
            old_fields=('ledger', 'content_key'),
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='idx_ledger_lms_content_exc',
            old_fields=('ledger', 'lms_user_id', 'content_key'),
        ),
        migrations.RenameIndex(
            model_name='transaction',
            new_name='idx_ledger_subsidy_exc',
            old_fields=('ledger', 'subsidy_access_policy_uuid'),
        ),
    ]
